Repository 2nnerPeace/The-Moon-Ha-Backend, pull requests merged in 2024-08, with the labels that each got.

#3 [LESSON] [KAN-12] 강좌 목록 조회 구현
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/vo/LessonTime.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#5 [LESSON] [KAN-17] 강좌 상세 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#8 [LESSON] [KAN-59] 금주의 1분 강좌(숏폼) 상세 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#10 [CRAFT] [KAN-61] 문화공방 메인 페이지 조회 구현
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/CraftMainResponse.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/PrologueDTO.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/SuggestionDTO.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/WishLessonDTO.java
  src/main/java/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftService.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/Criteria.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
Labels: Feat

#11 [AUTH] [KAN-11] 회원가입 API 구현
  .gitignore
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/auth/controller/AuthController.java
  src/main/java/com/innerpeace/themoonha/domain/auth/dto/SignUpRequest.java
  src/main/java/com/innerpeace/themoonha/domain/auth/mapper/AuthMapper.java
  src/main/java/com/innerpeace/themoonha/domain/auth/service/AuthService.java
  src/main/java/com/innerpeace/themoonha/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/auth/vo/MemberRole.java
  src/main/java/com/innerpeace/themoonha/global/config/PasswordEncoderConfig.java
  src/main/java/com/innerpeace/themoonha/global/dto/CommonResponse.java
  src/main/java/com/innerpeace/themoonha/global/entity/Member.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/auth/mapper/AuthMapper.xml
Labels: Feat

#15 [CRAFT] [KAN-15] 프롤로그 상세 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/PrologueDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftService.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
Labels: Feat

#16 [LOUNGE] [KAN-27] 라운지 목록 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/DateTimeUtil.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#21 [LESSON] [KAN-26] 장바구니 조회 및 담기 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/CartRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/CartResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#23 [AUTH] [KAN-11] 스프링 시큐리티 연결, JWT 초기 세팅
  .gitignore
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/auth/dto/JwtDTO.java
  src/main/java/com/innerpeace/themoonha/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/innerpeace/themoonha/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/innerpeace/themoonha/domain/auth/vo/MemberRole.java
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: Feat

#24 [LOUNGE] [KAN-28] 라운지 홈 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/AttendanceDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeHomeResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeInfoDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeMemberDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#28 [LESSON] [KAN-26] 강좌 수강 신청 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/SugangRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#26 [LOUNGE] [KAN-29] 라운지 게시글 상세 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeCommentDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostDetailDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#36 [COMMON] [KAN-20] S3 기능 구현
  pom.xml
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/S3Config.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/application-s3.properties
Labels: Feat

#37 [LOUNGE] [KAN-29] 라운지 게시글, 댓글 등록 기능 추가
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeCommentRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#40 [CRAFT] [KAN-21] 듣고싶은 강좌 투표 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftService.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
Labels: Feat

#44 [AUTH] [KAN-11] AuthMapper.xml 오류 수정
  src/main/resources/com/innerpeace/themoonha/domain/auth/mapper/AuthMapper.xml
Labels: Fix

#46 [LOUNGE] [KAN-29] S3 서비스 경로 설정, 파일 이름 설정
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#49 [AUTH] [KAN-11] security-context.xml filter 임시 해제
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Fix

#48 [BITE] [KAN-20] BeforeAfter 목록 조회, 검색, 업로드 기능 구현 및 S3 구조 수정
  .gitignore
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/BeforeAfterDTO.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/BeforeAfterHashtag.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/BeforeAfterRequest.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/BeforeAfterResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/BeforeAfterSearchResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/Hashtag.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/RedisConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/S3Config.java
  src/main/java/com/innerpeace/themoonha/global/exception/JsonTypeConvertException.java
  src/main/java/com/innerpeace/themoonha/global/exception/S3Exception.java
  src/main/java/com/innerpeace/themoonha/global/handler/CommaSeparatedStringToListTypeHandler.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/application-s3.properties
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/ehcache.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: Feat

#52 [LOUNGE] [KAN-29] 게시물 수정, 삭제 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#56 [Lounge] [KAN-31] 댓글 수정, 삭제 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeCommentUpdateRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeMemberDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#60 [LOUNGE] [KAN-33] 출석 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/AttendanceDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeMemberDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#57 [BITE] [KAN-20] 비포애프터 쿼리 포맷 변경
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
Labels: Style

#61 [LESSON] [KAN-12] 강좌 목록 조회 쿼리 및 로직 수정
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListRequest.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#62 [ADMIN] [KAN-14] 숏폼 등록 API 구현
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminLessonController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminShortFormController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/LessonAdminResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/LessonListAdminRequest.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/LessonRegisterAdminRequest.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/ShortFormRegisterAdminRequest.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminLessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminShortFormMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminLessonService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminShortFormService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminShortFormServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
  src/main/java/com/innerpeace/themoonha/global/entity/Lesson.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminLessonMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminShortFormMapper.xml
Labels: Feat

#66 [ADMIN] [KAN-16] 문화공방 프롤로그 테마 및 영상 등록, 조회
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminCraftController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminShortFormController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/PrologueListAdminResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/PrologueRegisterAdminRequest.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/PrologueThemeListAdminResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminCraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/entity/Prologue.java
  src/main/java/com/innerpeace/themoonha/global/handler/StringListTypeHandler.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminCraftMapper.xml
Labels: Feat

#68 [LESSON] [KAN-12] 강좌 목록 조회 로직 수정
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat
