Repository 2nnerPeace/The-Moon-Ha-Backend, pull requests merged in 2024-09, with the labels that each got.

#73 [LESSON] [KAN-59] Feat: 숏폼 상세 조회 API 제거 및 강좌 목록 조회 시 숏폼 DTO 필드 변경
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#70 [BITE] [KAN-23] 분야별 한입 강좌 목록, 검색, 상세 조회 및 등록 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterDTO.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterHashtag.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterRequest.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterResponseForDetail.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterResponseForList.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterSearchResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldDTO.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldHashtag.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldRequest.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldResponseForDetail.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldResponseForList.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldSearchResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/RedisConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/S3Config.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/exception/JsonTypeConvertException.java
  src/main/java/com/innerpeace/themoonha/global/exception/S3Exception.java
  src/main/java/com/innerpeace/themoonha/global/handler/CommaSeparatedStringToListTypeHandler.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Feat, Refactor, Chore

#74 [ADMIN] [KAN-18] 제안합니다 관리자 조회 API
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminCraftController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftServiceImpl.java
Labels: Feat

#75 [LIVE] [KAN-52] 실시간 강좌 및 채팅 기능 구현
  Dockerfile
  docker-compose.yml
  mvnw
  nginx.conf
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldDTO.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/controller/LiveChatController.java
  src/main/java/com/innerpeace/themoonha/domain/live/controller/LiveLessonController.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/ChatMessage.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonRequest.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonStatusResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/mapper/LiveChatMapper.java
  src/main/java/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/ChatService.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/ChatServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonEventConsumer.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonEventService.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonService.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/vo/LiveChat.java
  src/main/java/com/innerpeace/themoonha/domain/live/vo/LiveLesson.java
  src/main/java/com/innerpeace/themoonha/domain/live/vo/LiveSetting.java
  src/main/java/com/innerpeace/themoonha/domain/live/vo/LiveStatus.java
  src/main/java/com/innerpeace/themoonha/global/config/KafkaConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/RedisConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/WebSocketConfig.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/handler/StreamingWebSocketHandler.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/live/mapper/LiveChatMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#78 [LIVE] [KAN-52] 카프카 빈 설정 및 docker-compose 에러 해결
  .gitignore
  docker-compose.yml
  nginx.conf
  pom.xml
  src/main/java/com/innerpeace/themoonha/global/config/KafkaConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/StompWebSocketConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/StreamingWebSocketConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/WebSocketConfig.java
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Fix

#82 [BITE] [KAN-23] 비포애프터, 분야별 한 입 코드 수정
  docker-compose.yml
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/beforeafter/BeforeAfterListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Fix

#86 [LESSON] [KAN-25] 비포애프터에 등록 가능한 강좌 조회 API 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonEnrollResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#80 [CRAFT] [KAN-61] 문화공방 메인 페이지 프롤로그 조회 시 상세 조회 데이터도 가져오도록 변경
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/CraftMainResponse.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/PrologueDTO.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/PrologueDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/SuggestionResponse.java
  src/main/java/com/innerpeace/themoonha/domain/craft/dto/WishLessonDTO.java
  src/main/java/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftService.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/dto/PageDTO.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
Labels: Feat

#84 [COMMON] [KAN-60] CORS config 설정
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
  src/main/java/com/innerpeace/themoonha/global/config/WebConfig.java
  src/main/webapp/WEB-INF/spring/security-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: Feat

#87 [BITE] [KAN-23] 분야별 한 입 코드 수정
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/dto/field/FieldListResponse.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Fix

#93 [BITE] [KAN-23] 정렬 기능 추가
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Feat

#91 [ADMIN] [KAN-60] 지점별 강좌 리스트 데이터 불러오기
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/AdminDataResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/LessonBranchDTO.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminShortFormServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminMapper.xml
Labels: Feat

#95 [AUTH] [KAN-11] MemberId 어노테이션 추가
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminCraftController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/PrologueRegisterAdminRequest.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminCraftMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminCraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/auth/controller/AuthController.java
  src/main/java/com/innerpeace/themoonha/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/innerpeace/themoonha/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/innerpeace/themoonha/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
  src/main/java/com/innerpeace/themoonha/global/config/WebConfig.java
  src/main/java/com/innerpeace/themoonha/global/resolver/MemberIdResolver.java
  src/main/java/com/innerpeace/themoonha/global/util/MemberId.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminCraftMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/auth/mapper/AuthMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#97 [LESSON] [KAN-17] 강좌 상세 조회 응답 객체 온라인 비용 필드 추가
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/LessonDetailResponse.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#99 [ SCHEDULE] [KAN-34] 주간 스케줄 조회 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/controller/ScheduleController.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/dto/ScheduleWeeklyResponse.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleService.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#106 [LESSON] [KAN-58] 강사의 내 강좌 목록 조회 API 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/TutorLessonResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#101 [SCHEDULE] [KAN-34] 스케줄 월간 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/schedule/controller/ScheduleController.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/dto/ScheduleMonthlyResponse.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleService.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
Labels: Feat

#104 [LOUNGE] [KAN-28] 라운지 데이터 조회 시 회원 권한 적용
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeCommentDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeHomeResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeInfoDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungePostDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/DateTimeUtil.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#109 [SCHEDULE] [KAN-28] 다음 스케줄 보기 구현
  src/main/java/com/innerpeace/themoonha/domain/schedule/controller/ScheduleController.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/dto/ScheduleNextResponse.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleService.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
Labels: Feat

#103 [COMMON] [KAN-60] DB url 업로드 시 cloudfront url로 등록
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#111 [ADMIN] [KAN-13] 강좌 상세 조회 API 및 응답 데이터 추가
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminLessonController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/LessonDetailAdminResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminLessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminLessonService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminLessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminLessonMapper.xml
Labels: Feat

#115 [COMMON] [KAN-60] 배포 health-check 추가, origin 도메인 추가
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
  src/main/java/com/innerpeace/themoonha/global/config/WebConfig.java
  src/main/java/com/innerpeace/themoonha/global/controller/CheckController.java
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#116 [LOUNGE] [KAN-23] 출결 상태 조회 구현
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/AttendanceDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/AttendanceMembersDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/AttendanceMembersResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeHomeResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/DateTimeUtil.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#117 [LESSON] [KAN-12] 숏폼 목록 조회 시 지점 조건 추가
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#120 [COMMON] [KAN-60] origin 도메인 추가
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
Labels: Feat, Chore

#123 [COMMON] [KAN-60] CodeDeploy 실행용 appspec.yml과 deploy.sh 작성
  appspec.yml
  scripts/deploy.sh
Labels: Feat, Chore

#124 [COMMON] [KAN-60] overwrite 명령어 위치 변경
  appspec.yml
Labels: Fix, Chore

#125 [COMMON] [KAN-60] 큰 따옴표 이상 처리
  scripts/deploy.sh
Labels: Fix

#126 [COMMON] [KAN-60] PROJECT_ROOT 폴더명 수정
  scripts/deploy.sh
Labels: Fix

#128 [BITE] [KAN-20] 문화 한 입 쿼리 수정
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Fix

#129 [LESSON] [KAN-59] 숏폼 조회수 레디스 캐싱 + 스케줄링 + 배치 작업 구현
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftService.java
  src/main/java/com/innerpeace/themoonha/domain/craft/service/CraftServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/dto/ShortFormViewCountDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/scheduler/LessonScheduler.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/ChatServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/RedisConfig.java
  src/main/java/com/innerpeace/themoonha/global/config/SchedulerConfig.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/service/RedisViewService.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#133 [COMMON] XSS 방지 필터 적용
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/craft/controller/CraftController.java
  src/main/java/com/innerpeace/themoonha/global/xss/XSSFilter.java
  src/main/java/com/innerpeace/themoonha/global/xss/XSSFilterWrapper.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: Feat

#134 [ADMIN] [KAN-14] 퀴리 및 응답 데이터 수정
  src/main/java/com/innerpeace/themoonha/domain/admin/controller/AdminShortFormController.java
  src/main/java/com/innerpeace/themoonha/domain/admin/dto/ShortFormListAdminResponse.java
  src/main/java/com/innerpeace/themoonha/domain/admin/mapper/AdminShortFormMapper.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminShortFormService.java
  src/main/java/com/innerpeace/themoonha/domain/admin/service/AdminShortFormServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/admin/mapper/AdminShortFormMapper.xml
Labels: Feat

#138 [BITE] [KAN-20] 문화 한 입 코드 수정
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonDetailResponse.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.xml
Labels: Fix, Refactor

#141 [COMMON] [KAN-19] ci/cd package 구성 미리 하고 올리기
  scripts/deploy.sh
Labels: Chore

#142 [COMMON] [KAN-19] directory명 수정
  scripts/deploy.sh
Labels: Fix, Chore

#136 [ALIM] [KAN-37] 알림 기능 구현
  .gitignore
  pom.xml
  src/main/java/com/innerpeace/themoonha/domain/alim/controller/AlimController.java
  src/main/java/com/innerpeace/themoonha/domain/alim/controller/AlimScheduler.java
  src/main/java/com/innerpeace/themoonha/domain/alim/dto/LoungeAlimDTO.java
  src/main/java/com/innerpeace/themoonha/domain/alim/mapper/AlimMapper.java
  src/main/java/com/innerpeace/themoonha/domain/alim/service/AlimService.java
  src/main/java/com/innerpeace/themoonha/domain/alim/service/AlimServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/controller/ScheduleController.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/java/com/innerpeace/themoonha/global/util/FcmUtil.java
  src/main/java/com/innerpeace/themoonha/global/vo/SuccessCode.java
  src/main/resources/com/innerpeace/themoonha/domain/alim/mapper/AlimMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#144 [COMMON] [KAN-19] pom.xml Root.war 파일 생성
  pom.xml
Labels: Chore

#145 [COMMON] [KAN-19] ROOT.war 로 이름 바꾸기
  pom.xml
Labels: Chore

#146 [COMMON] [KAN-19] 리액트 연결을 위한 base url 추가
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
Labels: Chore

#147 [COMMON] [KAN-19] base url http 삭제
  src/main/java/com/innerpeace/themoonha/global/config/CORSFilter.java
Labels: Chore

#149 [AUTH] [KAN-11] JSESSIONID 생성 안되게 수정
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Chore

#151 [BITE] [KAN-20] 문화 한 입 MemberId 적용 및 DockerCompose 수정
  Dockerfile
  docker-compose.yml
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/BeforeAfterController.java
  src/main/java/com/innerpeace/themoonha/domain/bite/controller/FieldController.java
  src/main/java/com/innerpeace/themoonha/domain/live/controller/LiveLessonController.java
  src/main/java/com/innerpeace/themoonha/global/config/EnvironmentConfig.java
Labels: Fix, Refactor

#153 [LIVE] [KAN-55] 실시간 조회수, 좋아요 기능 보완
  docker-compose.yml
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonDetailResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonEventConsumer.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/vo/LiveLesson.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Fix, Feat, Refactor

#156 [LESSON] 강좌 메인페이지 조회 시 username이 아닌 name 반환하도록 변경
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/service/RedisViewService.java
  src/main/resources/com/innerpeace/themoonha/domain/craft/mapper/CraftMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat, Refactor

#158 [LIVE] [KAN-58] 문화한입, 실시간 코드 수정
  nginx.conf
  src/main/java/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/service/S3Service.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
Labels: Fix

#159 [LOUNGE] [KAN-28] 라운지 게시글 무한스크롤 구현
  src/main/java/com/innerpeace/themoonha/domain/alim/controller/AlimController.java
  src/main/java/com/innerpeace/themoonha/domain/alim/controller/AlimScheduler.java
  src/main/java/com/innerpeace/themoonha/domain/alim/mapper/AlimMapper.java
  src/main/java/com/innerpeace/themoonha/domain/alim/service/AlimServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/controller/LoungeController.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeCommentDTO.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/dto/LoungeHomeResponse.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeService.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/controller/ScheduleController.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/dto/ScheduleMonthlyResponse.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/dto/ScheduleWeeklyResponse.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleService.java
  src/main/java/com/innerpeace/themoonha/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/config/WebConfig.java
  src/main/java/com/innerpeace/themoonha/global/resolver/RoleResolver.java
  src/main/java/com/innerpeace/themoonha/global/util/DateTimeUtil.java
  src/main/java/com/innerpeace/themoonha/global/util/Role.java
  src/main/resources/com/innerpeace/themoonha/domain/alim/mapper/AlimMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: Feat

#163 [CART] 강좌 제거 기능 구현
  src/main/java/com/innerpeace/themoonha/domain/lesson/controller/LessonController.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonService.java
  src/main/java/com/innerpeace/themoonha/domain/lesson/service/LessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/exception/ErrorCode.java
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Feat

#171 [ALIM] [KAN-37] 알림 클릭 시 이동할 페이지 지정
  src/main/java/com/innerpeace/themoonha/domain/alim/service/AlimService.java
  src/main/java/com/innerpeace/themoonha/domain/alim/service/AlimServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/FcmUtil.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Feat

#173 [ALIM] [KAN-37] 알림에 보일 내용 수정
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/java/com/innerpeace/themoonha/global/util/FcmUtil.java
  src/main/resources/com/innerpeace/themoonha/domain/lounge/mapper/LoungeMapper.xml
Labels: Fix

#174 [BITE] [KAN-23] 분야별 한입 등록시 강좌 목록 불러오는 쿼리 수정
  src/main/resources/com/innerpeace/themoonha/domain/lesson/mapper/LessonMapper.xml
Labels: Fix

#177 [SCHEDULE] [KAN-24] 스케줄 불러올 때 라운지 참여 여부 반영
  src/main/java/com/innerpeace/themoonha/domain/lounge/service/LoungeServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/schedule/mapper/ScheduleMapper.xml
Labels: Fix

#181 [COMMON] [KAN-44] 주석 추가
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/beforeafter/BeforeAfterServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldService.java
  src/main/java/com/innerpeace/themoonha/domain/bite/service/field/FieldServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/controller/LiveLessonController.java
  src/main/java/com/innerpeace/themoonha/domain/live/dto/LiveLessonResponse.java
  src/main/java/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/ChatServiceImpl.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonService.java
  src/main/java/com/innerpeace/themoonha/domain/live/service/LiveLessonServiceImpl.java
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/BeforeAfterMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/bite/mapper/FieldMapper.xml
  src/main/resources/com/innerpeace/themoonha/domain/live/mapper/LiveLessonMapper.xml
Labels: Chore
